import { LastResult } from "./results/last-result";
import { Result } from "./results/result";
import { ResultCount } from "./results/result-count";

import { Milestone } from "./results/result-milestone";

export type TestSet = {
  _rallyAPIMajor: string;
  _rallyAPIMinor: string;
  _ref: string;
  _refObjectUUID: string;
  _objectVersion: string;
  _refObjectName: string;
  CreationDate: string;
  _CreatedAt: string;
  ObjectID: number;
  ObjectUUID: string;
  VersionId: string;
  Subscription: Result;
  Workspace: Result;
  Changesets: ResultCount;
  Connections: ResultCount;
  CreatedBy: Result;
  Description: string;
  Discussion: ResultCount;
  DisplayColor: string;
  Expedite: boolean;
  FormattedID: string;
  LastUpdateDate: string;
  LatestDiscussionAgeInMinutes: any;
  Milestones: Milestone;
  Name: string;
  Notes: string;
  Owner: Result;
  Project: Result;
  Ready: boolean;
  RevisionHistory: LastResult;
  Tags: Milestone;
  AcceptedDate: any;
  Blocker: any;
  FlowState: Result;
  FlowStateChangedDate: string;
  ScheduleState: string;
  ScheduleStatePrefix: string;
  TaskActualTotal: number;
  TaskEstimateTotal: number;
  TaskRemainingTotal: number;
  Blocked: boolean;
  BlockedReason: any;
  DefectStatus: string;
  DragAndDropRank: string;
  Iteration: Result;
  LastBuild: string;
  LastRun: string;
  PassingTestCaseCount: number;
  PlanEstimate: any;
  Release: any;
  TaskStatus: string;
  Tasks: ResultCount;
  TestCaseCount: number;
  TestCaseStatus: string;
  TestCases: ResultCount;
  c_ComponentDRFIS: any;
  Errors: Array<any>;
  Warnings: Array<any>;
};
